export default [
  {
    id: "1",
    title: "The Lean Startup",
    author: "Eric Ries",
    description: "A methodology for developing businesses and products.",
    cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1629999184i/10127019.jpg",
    genre: "Business",
    uploadedBy: "Alice",
    image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1629999184i/10127019.jpg",
    background: "hsl(210, 70%, 90%)",
    voters: "856",
    stars: [4, 5, 4, 4, 5]
  },
  {
    id: "2",
    title: "Zero to One",
    author: "Peter Thiel",
    description: "Notes on startups, or how to build the future.",
    cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1630663027i/18050143.jpg",
    genre: "Business",
    uploadedBy: "Bob",
    image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1630663027i/18050143.jpg",
    background: "hsl(180, 70%, 90%)",
    voters: "723",
    stars: [5, 5, 4, 4, 5]
  },
  {
    id: "3",
    title: "Dune",
    author: "Frank Herbert",
    description: "Epic science fiction set on the desert planet Arrakis.",
    cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1555447414i/44767458.jpg",
    genre: "Science Fiction",
    uploadedBy: "Charlie",
    image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1555447414i/44767458.jpg",
    background: "hsl(150, 70%, 90%)",
    voters: "945",
    stars: [5, 5, 5, 4, 5]
  },
  {
    id: "4",
    title: "Neuromancer",
    author: "William Gibson",
    description: "Cyberpunk classic about a hacker in a dystopian future.",
    cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1752514552i/6088007.jpg",
    genre: "Science Fiction",
    uploadedBy: "Alice",
    image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1752514552i/6088007.jpg",
    background: "hsl(120, 70%, 90%)",
    voters: "678",
    stars: [4, 4, 5, 4, 4]
  },
  {
    id: "5",
    title: "Meditations",
    author: "Marcus Aurelius",
    description: "Philosophical writings by the Roman emperor.",
    cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1421618636i/30659.jpg",
    genre: "Philosophy",
    uploadedBy: "Bob",
    image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1421618636i/30659.jpg",
    background: "hsl(90, 70%, 90%)",
    voters: "567",
    stars: [5, 5, 4, 5, 5]
  },
  {
    id: "6",
    title: "The Republic",
    author: "Plato",
    description: "Classic philosophical text discussing justice and the ideal state.",
    cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1386925655i/30289.jpg",
    genre: "Philosophy",
    uploadedBy: "Charlie",
    image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1386925655i/30289.jpg",
    background: "hsl(60, 70%, 90%)",
    voters: "789",
    stars: [4, 5, 4, 4, 4]
  },
  {
    id: "7",
    title: "Steve Jobs",
    author: "Walter Isaacson",
    description: "Biography of Apple co-founder Steve Jobs.",
    cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1511288482i/11084145.jpg",
    genre: "Biography",
    uploadedBy: "Alice",
    image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1511288482i/11084145.jpg",
    background: "hsl(30, 70%, 90%)",
    voters: "432",
    stars: [5, 4, 5, 5, 4]
  },
  {
    id: "8",
    title: "Elon Musk",
    author: "Ashlee Vance",
    description: "Biography of Elon Musk, CEO of SpaceX and Tesla.",
    cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1518291452i/25541028.jpg",
    genre: "Biography",
    uploadedBy: "Bob",
    image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1518291452i/25541028.jpg",
    background: "hsl(0, 70%, 90%)",
    voters: "321",
    stars: [4, 5, 4, 4, 5]
  },
  {
    id: "9",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    description: "Explores the two systems that drive human thinking.",
    cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1317793965i/11468377.jpg",
    genre: "Business",
    uploadedBy: "Charlie",
    image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1317793965i/11468377.jpg",
    background: "hsl(240, 70%, 90%)",
    voters: "654",
    stars: [5, 4, 5, 5, 4]
  },
  {
    id: "10",
    title: "The Innovators",
    author: "Walter Isaacson",
    description: "The story of the people who created the computer and the Internet.",
    cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1410191571i/21856367.jpg",
    genre: "Business",
    uploadedBy: "Alice",
    image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1410191571i/21856367.jpg",
    background: "hsl(210, 70%, 90%)",
    voters: "432",
    stars: [4, 5, 4, 4, 5]
  },
  {
    id: "11",
    title: "Foundation",
    author: "Isaac Asimov",
    description: "Science fiction series about the fall and rise of a galactic empire.",
    cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1417900846i/29579.jpg",
    genre: "Science Fiction",
    uploadedBy: "Bob",
    image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1417900846i/29579.jpg",
    background: "hsl(180, 70%, 90%)",
    voters: "789",
    stars: [5, 4, 5, 5, 4]
  },
  {
    id: "12",
    title: "Brave New World",
    author: "Aldous Huxley",
    description: "Dystopian novel exploring a technologically controlled society.",
    cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1575509280i/5129.jpg",
    genre: "Science Fiction",
    uploadedBy: "Charlie",
    image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1575509280i/5129.jpg",
    background: "hsl(150, 70%, 90%)",
    voters: "654",
    stars: [4, 5, 4, 4, 5]
  },
  {
    id: "13",
    title: "Beyond Good and Evil",
    author: "Friedrich Nietzsche",
    description: "Philosophical work challenging traditional morality.",
    cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1388607391i/12321.jpg",
    genre: "Philosophy",
    uploadedBy: "Alice",
    image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1348640754i/12261384.jpg",
    background: "hsl(120, 70%, 90%)",
    voters: "543",
    stars: [5, 4, 5, 5, 4]
  },
  {
    id: "14",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    description: "A brief history of humankind.",
    cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1420585954i/23692271.jpg",
    genre: "Biography",
    uploadedBy: "Bob",
    image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1420585954i/23692271.jpg",
    background: "hsl(90, 70%, 90%)",
    voters: "876",
    stars: [5, 4, 5, 5, 4]
  },
  {
    id: "15",
    title: "Educated",
    author: "Tara Westover",
    description: "Memoir about growing up in a strict and abusive household.",
    cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1506026635i/35133922.jpg",
    genre: "Biography",
    uploadedBy: "Charlie",
    image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1506026635i/35133922.jpg",
    background: "hsl(60, 70%, 90%)",
    voters: "432",
    stars: [4, 5, 4, 4, 5]
  },
  {
    id: "16",
    title: "Principles",
    author: "Ray Dalio",
    description: "Life and work principles from a billionaire investor.",
    cover: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1503365703i/34536488.jpg",
    genre: "Business",
    uploadedBy: "Alice",
    image: "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1503365703i/34536488.jpg",
    background: "hsl(30, 70%, 90%)",
    voters: "321",
    stars: [5, 4, 5, 5, 4]
  }
];